### ISSUE TITLE
[O-02] Executar funcionalidades do Executor de Polinômios - BACKEND

### ISSUE THREAD

**Issue by jose-luan19** [Rudigus/projeto-orbit#7]
- [x] Definir as operações matemáticas possíveis

- [x] Criar objeto Mockado de equações complexas, que atendam a todas as possibilidades.

- [x] Criar classes necessárias para a classe Polinômio - Model
 
- [x] Executar os polinómios mockados para determinados valores numérico de incógnita: x = 2

**Comment by Gutemberg370** [comment]
class Monomio {
    constructor(_coeficiente = 1  ,_incognita = "x",_expoenteIncognita = 0){
        this._coeficiente = _coeficiente;
        this._incognita = _incognita;
        this._expoenteIncognita = _expoenteIncognita;
        
    }
}

class Polinomio{
    constructor(_monomio = []){
        this._monomio = _monomio;
    }
}

class Equacao{
    constructor(_polinomioEsquerda , _polinomioDireita){
        this._polinomioEsquerda = _polinomioEsquerda;
        this._polinomioDireita = _polinomioDireita;
    }
}

class Resolucao{
    cosntructor(_passos = [], _resultado){
        this._passos = _passos;
        this._resultado = _resultado;
    }
}

class Cabecalho{
    constructor(_assunto, _materia,_formula,_exemplo = [],_resolucao,_nomeParametros){
        this.assunto = _assunto;
        this.materia = _materia;
        this._formula = _formula;
        this._exemplo = _exemplo;
        this._resolucao = _resolucao;
        this._nomeParametros = _nomeParametros;
     }
     elaborarResolucao(_polinomioEsquerda,_polinomioDireita){
         var i , a = 0 , b = 0, c = 0, R1 = 0 , R2 = 0;
         var Res = [];

         for(i = 0 ; i < 3; i++){
             if(_polinomioEsquerda[i]._expoenteIncognita == 2){
                 a += _polinomioEsquerda[i]._coeficiente;
                 return console.log(a);
             }
             if(_polinomioEsquerda[i]._expoenteIncognita == 1){
                b += _polinomioEsquerda[i]._coeficiente;
            }
            if(_polinomioEsquerda[i]._expoenteIncognita == 0){
                c += _polinomioEsquerda[i]._coeficiente;
            }
        }
            for(i = 0 ; i < _polinomioDireita.length; i++){
                if(_polinomioEsquerda[i]._expoenteIncognita = 2){
                    a -= _polinomioEsquerda[i]._coeficiente;
                }
                if(_polinomioEsquerda[i]._expoenteIncognita = 1){
                   b -= _polinomioEsquerda[i]._coeficiente;
               }
               if(_polinomioEsquerda[i]._expoenteIncognita = 0){
                   c -= _polinomioEsquerda[i]._coeficiente;
               }

         }
         R1 = (-b+Math.round(Math.sqrt(b**2-4*a*c)*100)/100)/2*a;
         R2 = (-b-Math.round(Math.sqrt(b**2-4*a*c)*100)/100)/2*a;
         

         return console.log(R1, R2, a, b, c);
         
     }
}

var Monomio1 = new Monomio(3,"x",2);
var Monomio2 = new Monomio(4,"x",1);
var Monomio3 = new Monomio(2,"x",0);
var Monomio4 = new Monomio(Math.round(Math.sqrt(2)*100)/100);
var Monomio5 = new Monomio(0,"x",0);


var Polinomio1 = [Monomio1, Monomio2, Monomio3];
var Polinomio2 = [Monomio5];


var Polinomio3 = new Polinomio(Polinomio1);
var Polinomio4 = new Polinomio(Polinomio2);

var Equacao1 = new Equacao(Polinomio3,Polinomio4);

var exemplo1 = ["X^2-X-8=0", "X^2-4=0" , "3X^2-4X-7=0" , "5^(1\2)X^2-4X+3=0" , "1\2X^2+3\4X+3^(3\2)"];

var Resolucao1 = new Resolucao()

var Cabecalho1 = new Cabecalho("Equações do 2º Grau","Matemática","x = (-b±sqrt(b^2-4ac)/2a ", exemplo1, ,"f(x) = a*x**2 + b*x + c");

Cabecalho1.elaborarResolucao(Polinomio3,Polinomio4);

console.log(Polinomio[3]._expoenteIncognita);
