### ISSUE TITLE
[O-04] Estudar o padrão de design do React JS

### ISSUE THREAD

**Issue by jose-luan19** [Rudigus/projeto-orbit#8]
- [x] Fazer o curso de React JS

**Comment by matheusb432** [comment]
Estudo das funcionalidades do React JS por meio de tutoriais passo a passo:

Calculadora de botões simples: 
https://medium.com/@nitinpatel_20236/how-to-build-a-simple-calculator-application-with-react-js-bc10a4568bbd

Jogo da velha, exercitado no pencode, para melhor entender as funcionalidades da biblioteca:
https://reactjs.org/tutorial/tutorial.html#setup-option-2-local-development-environment

**Comment by matheusb432** [comment]
Código praticado no React JS com estilização CSS, utilizando Stylesheets:
App.js:
```
import React, { Component } from 'react';
import './App.css';
import Stylesheet from './components/Stylesheet';

class App extends Component {
 
  render() {
      return (
          <div className = "App">
              <Stylesheet fontXl={true}/>
              {/* fontXl e true, logo a condicional presente na componente Stylesheet e obedecida e a fonte sera alterada conforme a funcao no arquivo CSS. */}
          </div>
      );
  }
}
export default App:
```
Componentes:

Stylesheet.js:
```
import React from 'react'
import './myStyles.css'

function Stylesheet(props) {
     let className = props.fontXl ? 'fontXl': ''
     //    argumento condicional '?' 'verdade' : 'falso' //
   return(
    <div>
      <h1 className={`${className} primary`}>Teste</h1>
    </div>

   ) 
}
export default Stylesheet


```
myStyles.css:
```
.primary {
    color: darkblue;
}

.fontXl {
   font-size: 72px;
}

```
O código deverá então exibir, no servidor local onde o React está sendo executado, a palavra "Teste" com tamanho 72px e a cor azul escura.

**Comment by matheusb432** [comment]
Setup do React em um dispositivo com IDE apropriado e Node.js já instalados, todos comandos abaixo deverão ser inseridos no cmd do dispositivo:

1. npx create-react-app {nome do projeto}

2. cd {nome do projeto}

3. code ( etapa que abre o react no VS Code para facilitar o setup )

4. npm start ( abre o servidor local onde será trabalho o React, deverá ser o localhost:3000. )

**Comment by matheusb432** [comment]
Outra maneira de trabalhar com CSS no React JS, nesse caso, maneira Inline: 
App.js:
```
import React, { Component } from 'react';
import './App.css';
import Inline from './components/Inline';

class App extends Component {
 
  render() {
      return (
          <div className = "App">
              <Inline />
          </div>
      );
  }
}
export default App;

```

Componentes:

Inline.js:
```
import React from 'react'

const heading = {
    fontSize: '72px',
    color: 'purple'
}

function Inline() {
    return (
        <div>
            <h1 style={heading}> Inline </h1>
            {/* atributo style igual ao objeto heading */}
        </div>
    )
}

export default Inline

```
